# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Refugee.delete_all
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Australia", refugees: 7785 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Austria", refugees: 17458 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Belgium", refugees: 2934 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Canada", refugees: 2890 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Denmark", refugees: 2166 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Finland",	refugees: 1406 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"France", refugees: 4397 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Germany",	refugees: 30026 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Greece", refugees: 5223 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Hungary",	refugees: 942 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"India",	refugees: 10196 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Indonesia",	refugees: 2890 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Iran", refugees: 952 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Italy",	refugees: 12203 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Netherlands",	refugees: 5803)
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Norway", refugees: 5684)
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Pakistan", refugees: 1560592)
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Serbia and Kosovo", refugees: 1999 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Sweden", refugees: 13064 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Switzerland", refugees: 4686 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Syria", refugees: 1213 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Tajikistan", refugees: 1950 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Turkey", refugees: 3846 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"Ukraine", refugees: 1520 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"United Kingdom", refugees: 9354 )
Refugee.create(countryOfOrigin:"Afghanistan", countryOfAsylum:"United States of America", refugees: 1361 )
Refugee.create(countryOfOrigin:"Albania", countryOfAsylum:"France", refugees: 2911 )
Refugee.create(countryOfOrigin:"Albania", countryOfAsylum:"United Kingdom", refugees: 1823 )
Refugee.create(countryOfOrigin:"Albania", countryOfAsylum:"United States of America", refugees: 2194 )
Refugee.create(countryOfOrigin:"Algeria", countryOfAsylum:"France", refugees: 1384 )
Refugee.create(countryOfOrigin:"Angola", countryOfAsylum:"Brazil", refugees: 1083 )
Refugee.create(countryOfOrigin:"Angola", countryOfAsylum:"France", refugees: 3349 )
Refugee.create(countryOfOrigin:"Armenia", countryOfAsylum:"France", refugees: 4034 )
Refugee.create(countryOfOrigin:"Armenia", countryOfAsylum:"Germany", refugees: 1191 )
Refugee.create(countryOfOrigin:"Armenia", countryOfAsylum:"United States of America", refugees: 2440 )
Refugee.create(countryOfOrigin:"Azerbaijan", countryOfAsylum:"Armenia", refugees: 1501 )
Refugee.create(countryOfOrigin:"Azerbaijan", countryOfAsylum:"France", refugees: 2816 )
Refugee.create(countryOfOrigin:"Azerbaijan", countryOfAsylum:"Germany", refugees: 2171 )
Refugee.create(countryOfOrigin:"Bangladesh", countryOfAsylum:"France", refugees: 3960 )
Refugee.create(countryOfOrigin:"Bangladesh", countryOfAsylum:"Italy", refugees: 2545 )
Refugee.create(countryOfOrigin:"Bangladesh", countryOfAsylum:"United Kingdom", refugees: 940 )
Refugee.create(countryOfOrigin:"Bangladesh", countryOfAsylum:"United States of America", refugees: 1121 )
Refugee.create(countryOfOrigin:"Belarus", countryOfAsylum:"United States of America", refugees: 1804 )
Refugee.create(countryOfOrigin:"Bhutan", countryOfAsylum:"Nepal", refugees: 17134 )
Refugee.create(countryOfOrigin:"Bosnia and Herzegovina", countryOfAsylum:"France", refugees: 4055 )
Refugee.create(countryOfOrigin:"Bosnia and Herzegovina", countryOfAsylum:"Germany", refugees: 1412 )
Refugee.create(countryOfOrigin:"Bosnia and Herzegovina", countryOfAsylum:"Serbia and Kosovo", refugees: 9287 )
Refugee.create(countryOfOrigin:"Bosnia and Herzegovina", countryOfAsylum:"Switzerland", refugees: 2274 )
Refugee.create(countryOfOrigin:"Burkina Faso", countryOfAsylum:"United States of America", refugees: 929 )
Refugee.create(countryOfOrigin:"Burundi", countryOfAsylum:"Canada", refugees: 2074 )
Refugee.create(countryOfOrigin:"Burundi", countryOfAsylum:"Congo", refugees: 23163 )
Refugee.create(countryOfOrigin:"Burundi", countryOfAsylum:"Kenya", refugees: 848 )
Refugee.create(countryOfOrigin:"Burundi", countryOfAsylum:"Malawi", refugees: 1479 )
Refugee.create(countryOfOrigin:"Burundi", countryOfAsylum:"Rwanda", refugees: 70848 )
Refugee.create(countryOfOrigin:"Burundi", countryOfAsylum:"South Africa", refugees: 3819 )
Refugee.create(countryOfOrigin:"Burundi", countryOfAsylum:"Uganda", refugees: 26256 )
Refugee.create(countryOfOrigin:"Burundi", countryOfAsylum:"Tanzania", refugees: 155755 )
Refugee.create(countryOfOrigin:"Burundi", countryOfAsylum:"Zambia", refugees: 2931 )
Refugee.create(countryOfOrigin:"Cambodia", countryOfAsylum:"France", refugees: 11824 )
Refugee.create(countryOfOrigin:"Cameroon", countryOfAsylum:"United States of America", refugees: 4530 )
Refugee.create(countryOfOrigin:"Central African Rep.", countryOfAsylum:"Cameroon", refugees: 267463 )
Refugee.create(countryOfOrigin:"Central African Rep.", countryOfAsylum:"Chad", refugees: 63397 )
Refugee.create(countryOfOrigin:"Central African Rep.", countryOfAsylum:"Congo", refugees: 23664 )
Refugee.create(countryOfOrigin:"Central African Rep.", countryOfAsylum:"Congo", refugees: 107929 )
Refugee.create(countryOfOrigin:"Central African Rep.", countryOfAsylum:"France", refugees: 1607 )
Refugee.create(countryOfOrigin:"Central African Rep.", countryOfAsylum:"South Sudan", refugees: 1882 )
Refugee.create(countryOfOrigin:"Central African Rep.", countryOfAsylum:"Sudan", refugees: 1439 )
Refugee.create(countryOfOrigin:"Chad", countryOfAsylum:"Cameroon", refugees: 1798 )
Refugee.create(countryOfOrigin:"Chad", countryOfAsylum:"France", refugees: 1232 )
Refugee.create(countryOfOrigin:"Chad", countryOfAsylum:"Sudan", refugees: 8894 )
Refugee.create(countryOfOrigin:"China", countryOfAsylum:"Australia", refugees: 2955 )
Refugee.create(countryOfOrigin:"China", countryOfAsylum:"Belgium", refugees: 1305 )
Refugee.create(countryOfOrigin:"China", countryOfAsylum:"Canada", refugees: 11415 )
Refugee.create(countryOfOrigin:"China", countryOfAsylum:"France", refugees: 3260 )
Refugee.create(countryOfOrigin:"China", countryOfAsylum:"Germany", refugees: 1406 )
Refugee.create(countryOfOrigin:"China", countryOfAsylum:"India", refugees: 110098 )
Refugee.create(countryOfOrigin:"China", countryOfAsylum:"Netherlands", refugees: 1236 )
Refugee.create(countryOfOrigin:"China", countryOfAsylum:"Switzerland", refugees: 3022 )
Refugee.create(countryOfOrigin:"China", countryOfAsylum:"United Kingdom", refugees: 1837 )
Refugee.create(countryOfOrigin:"China", countryOfAsylum:"United States of America", refugees: 74020 )
Refugee.create(countryOfOrigin:"Colombia", countryOfAsylum:"Brazil", refugees: 1280 )
Refugee.create(countryOfOrigin:"Colombia", countryOfAsylum:"Canada", refugees: 13666 )
Refugee.create(countryOfOrigin:"Colombia", countryOfAsylum:"Chile", refugees: 1054 )
Refugee.create(countryOfOrigin:"Colombia", countryOfAsylum:"Costa Rica", refugees: 2247 )
Refugee.create(countryOfOrigin:"Colombia", countryOfAsylum:"Ecuador", refugees: 120685 )
Refugee.create(countryOfOrigin:"Colombia", countryOfAsylum:"Panama", refugees: 15593 )
Refugee.create(countryOfOrigin:"Colombia", countryOfAsylum:"United States of America", refugees: 8043 )
Refugee.create(countryOfOrigin:"Colombia", countryOfAsylum:"Venezuela", refugees: 173673 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"France", refugees: 3225 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"South Africa", refugees: 6566 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"United States of America", refugees: 1344 )
Refugee.create(countryOfOrigin:"Côte d'Ivoire", countryOfAsylum:"France", refugees: 2654 )
Refugee.create(countryOfOrigin:"Côte d'Ivoire", countryOfAsylum:"Ghana", refugees: 10807 )
Refugee.create(countryOfOrigin:"Côte d'Ivoire", countryOfAsylum:"Guinea", refugees: 6668 )
Refugee.create(countryOfOrigin:"Côte d'Ivoire", countryOfAsylum:"Italy", refugees: 5079 )
Refugee.create(countryOfOrigin:"Côte d'Ivoire", countryOfAsylum:"Liberia", refugees: 36041 )
Refugee.create(countryOfOrigin:"Côte d'Ivoire", countryOfAsylum:"Togo", refugees: 2516 )
Refugee.create(countryOfOrigin:"Côte d'Ivoire", countryOfAsylum:"United States of America", refugees: 1574 )
Refugee.create(countryOfOrigin:"Croatia", countryOfAsylum:"Bosnia and Herzegovina", refugees: 6679 )
Refugee.create(countryOfOrigin:"Croatia", countryOfAsylum:"Serbia and Kosovo", refugees: 25962 )
Refugee.create(countryOfOrigin:"Cuba", countryOfAsylum:"Panama", refugees: 1118 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Angola", refugees: 12944 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Belgium", refugees: 1008 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Brazil", refugees: 1045 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Burundi", refugees: 53029 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Canada", refugees: 3316 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Central African Rep.", refugees: 4798 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Congo", refugees: 12267 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"France", refugees: 14182 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Germany", refugees: 1537 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Kenya", refugees: 12046 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Malawi", refugees: 5361 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Mozambique", refugees: 3415 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Namibia", refugees: 1313 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Rwanda", refugees: 73864 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"South Africa", refugees: 32582 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"South Sudan", refugees: 15916 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Switzerland", refugees: 1346 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Uganda", refugees: 201782 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"United Kingdom", refugees: 1473 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Tanzania", refugees: 55803 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Zambia", refugees: 19293 )
Refugee.create(countryOfOrigin:"Congo", countryOfAsylum:"Zimbabwe", refugees: 5414 )
Refugee.create(countryOfOrigin:"Egypt", countryOfAsylum:"Australia", refugees: 1507 )
Refugee.create(countryOfOrigin:"Egypt", countryOfAsylum:"Canada", refugees: 752 )
Refugee.create(countryOfOrigin:"Egypt", countryOfAsylum:"Germany", refugees: 636 )
Refugee.create(countryOfOrigin:"Egypt", countryOfAsylum:"Italy", refugees: 1397 )
Refugee.create(countryOfOrigin:"Egypt", countryOfAsylum:"United States of America", refugees: 10852 )
Refugee.create(countryOfOrigin:"El Salvador", countryOfAsylum:"Canada", refugees: 1403 )
Refugee.create(countryOfOrigin:"El Salvador", countryOfAsylum:"Mexico", refugees: 946 )
Refugee.create(countryOfOrigin:"El Salvador", countryOfAsylum:"United States of America", refugees: 11273 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Belgium", refugees: 700 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Canada", refugees: 1811 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Denmark", refugees: 3213 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Egypt", refugees: 1405 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Ethiopia", refugees: 155231 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"France", refugees: 2208 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Germany", refugees: 10980 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Israel", refugees: 27812 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Italy", refugees: 11962 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Kenya", refugees: 1229 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Netherlands", refugees: 10870 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Norway", refugees: 13490 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"South Africa", refugees: 2338 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Sudan", refugees: 98676 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Sweden", refugees: 20203 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Switzerland", refugees: 21000 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Uganda", refugees: 3401 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"United Kingdom", refugees: 12383 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"United States of America", refugees: 4085 )
Refugee.create(countryOfOrigin:"Eritrea", countryOfAsylum:"Yemen", refugees: 1278 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"Canada", refugees: 2047 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"Egypt", refugees: 1085 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"Germany", refugees: 2657 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"Italy", refugees: 1894 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"Kenya", refugees: 21229 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"Norway", refugees: 2012 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"Somalia", refugees: 2756 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"South Africa", refugees: 20324 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"South Sudan", refugees: 4200 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"Sudan", refugees: 3194 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"Sweden", refugees: 901 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"Switzerland", refugees: 1019 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"Uganda", refugees: 1495 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"United Kingdom", refugees: 1006 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"United States of America", refugees: 10566 )
Refugee.create(countryOfOrigin:"Ethiopia", countryOfAsylum:"Yemen", refugees: 5645 )
Refugee.create(countryOfOrigin:"Gambia", countryOfAsylum:"Italy", refugees: 4919 )
Refugee.create(countryOfOrigin:"Gambia", countryOfAsylum:"United Kingdom", refugees: 1235 )
Refugee.create(countryOfOrigin:"Gambia", countryOfAsylum:"United States of America", refugees: 1371 )
Refugee.create(countryOfOrigin:"Georgia", countryOfAsylum:"France", refugees: 2826 )
Refugee.create(countryOfOrigin:"Ghana", countryOfAsylum:"Italy", refugees: 2502 )
Refugee.create(countryOfOrigin:"Ghana", countryOfAsylum:"Togo", refugees: 18476 )
Refugee.create(countryOfOrigin:"Guatemala", countryOfAsylum:"United States of America", refugees: 8864 )
Refugee.create(countryOfOrigin:"Guinea", countryOfAsylum:"Belgium", refugees: 3150 )
Refugee.create(countryOfOrigin:"Guinea", countryOfAsylum:"France", refugees: 6005 )
Refugee.create(countryOfOrigin:"Guinea", countryOfAsylum:"Italy", refugees: 1626 )
Refugee.create(countryOfOrigin:"Guinea", countryOfAsylum:"United States of America", refugees: 2862 )
Refugee.create(countryOfOrigin:"Haiti", countryOfAsylum:"Canada", refugees: 8807 )
Refugee.create(countryOfOrigin:"Haiti", countryOfAsylum:"France", refugees: 3445 )
Refugee.create(countryOfOrigin:"Haiti", countryOfAsylum:"United States of America", refugees: 21508 )
Refugee.create(countryOfOrigin:"Honduras", countryOfAsylum:"Mexico", refugees: 727 )
Refugee.create(countryOfOrigin:"Honduras", countryOfAsylum:"United States of America", refugees: 4918 )
Refugee.create(countryOfOrigin:"Hungary", countryOfAsylum:"Canada", refugees: 973 )
Refugee.create(countryOfOrigin:"India", countryOfAsylum:"Canada", refugees: 3712 )
Refugee.create(countryOfOrigin:"India", countryOfAsylum:"United States of America", refugees: 4581 )
Refugee.create(countryOfOrigin:"Indonesia", countryOfAsylum:"Papua New Guinea", refugees: 9368 )
Refugee.create(countryOfOrigin:"Indonesia", countryOfAsylum:"United States of America", refugees: 3183 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"Australia", refugees: 5201 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"Austria", refugees: 3379 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"Canada", refugees: 2639 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"Denmark", refugees: 2009 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"France", refugees: 2417 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"Germany", refugees: 19763 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"Iraq", refugees: 8231 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"Italy", refugees: 1573 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"Netherlands", refugees: 4125 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"Norway", refugees: 1487 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"Sweden", refugees: 4232 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"Switzerland", refugees: 1604 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"Turkey", refugees: 5262 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"United Kingdom", refugees: 12667 )
Refugee.create(countryOfOrigin:"Iran", countryOfAsylum:"United States of America", refugees: 5216 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Armenia", refugees: 1019 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Australia", refugees: 2925 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Austria", refugees: 3732 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Belgium", refugees: 1943 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Bulgaria", refugees: 1339 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Canada", refugees: 1892 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Egypt", refugees: 4347 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Finland", refugees: 4124 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"France", refugees: 4787 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Germany", refugees: 51396 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Greece", refugees: 4348 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Iran", refugees: 28268 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Italy", refugees: 3428 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Jordan", refugees: 33256 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Lebanon", refugees: 7234 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Libya", refugees: 2507 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Netherlands", refugees: 12397 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Norway", refugees: 4916 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Serbia and Kosovo", refugees: 7 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Sweden", refugees: 23886 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Switzerland", refugees: 3501 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Syria", refugees: 18253 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Turkey", refugees: 24135 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"United Kingdom", refugees: 3014 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"United States of America", refugees: 5760 )
Refugee.create(countryOfOrigin:"Iraq", countryOfAsylum:"Yemen", refugees: 3404 )
Refugee.create(countryOfOrigin:"Kenya", countryOfAsylum:"Ethiopia", refugees: 3193 )
Refugee.create(countryOfOrigin:"Kenya", countryOfAsylum:"United States of America", refugees: 2258 )
Refugee.create(countryOfOrigin:"Kyrgyzstan", countryOfAsylum:"United States of America", refugees: 986 )
Refugee.create(countryOfOrigin:"Laos", countryOfAsylum:"France", refugees: 6944 )
Refugee.create(countryOfOrigin:"Liberia", countryOfAsylum:"Ghana", refugees: 2788 )
Refugee.create(countryOfOrigin:"Liberia", countryOfAsylum:"United States of America", refugees: 1266 )
Refugee.create(countryOfOrigin:"Libya", countryOfAsylum:"Malta", refugees: 1544 )
Refugee.create(countryOfOrigin:"Libya", countryOfAsylum:"United Kingdom", refugees: 1138 )
Refugee.create(countryOfOrigin:"Mali", countryOfAsylum:"Burkina Faso", refugees: 33574 )
Refugee.create(countryOfOrigin:"Mali", countryOfAsylum:"France", refugees: 4050 )
Refugee.create(countryOfOrigin:"Mali", countryOfAsylum:"Italy", refugees: 8334 )
Refugee.create(countryOfOrigin:"Mali", countryOfAsylum:"Mauritania", refugees: 50233 )
Refugee.create(countryOfOrigin:"Mali", countryOfAsylum:"Niger", refugees: 56012 )
Refugee.create(countryOfOrigin:"Mali", countryOfAsylum:"United States of America", refugees: 1239 )
Refugee.create(countryOfOrigin:"Mauritania", countryOfAsylum:"France", refugees: 5066 )
Refugee.create(countryOfOrigin:"Mauritania", countryOfAsylum:"Mali", refugees: 13539 )
Refugee.create(countryOfOrigin:"Mauritania", countryOfAsylum:"Senegal", refugees: 13687 )
Refugee.create(countryOfOrigin:"Mexico", countryOfAsylum:"Canada", refugees: 6414 )
Refugee.create(countryOfOrigin:"Mexico", countryOfAsylum:"United States of America", refugees: 4822 )
Refugee.create(countryOfOrigin:"Myanmar", countryOfAsylum:"Bangladesh", refugees: 231948 )
Refugee.create(countryOfOrigin:"Myanmar", countryOfAsylum:"India", refugees: 15735 )
Refugee.create(countryOfOrigin:"Myanmar", countryOfAsylum:"Japan", refugees: 1826 )
Refugee.create(countryOfOrigin:"Myanmar", countryOfAsylum:"Malaysia", refugees: 88637 )
Refugee.create(countryOfOrigin:"Myanmar", countryOfAsylum:"Thailand", refugees: 106349 )
Refugee.create(countryOfOrigin:"Myanmar", countryOfAsylum:"United States of America", refugees: 1999 )
Refugee.create(countryOfOrigin:"Nepal", countryOfAsylum:"United States of America", refugees: 6605 )
Refugee.create(countryOfOrigin:"Nigeria", countryOfAsylum:"Cameroon", refugees: 71840 )
Refugee.create(countryOfOrigin:"Nigeria", countryOfAsylum:"Canada", refugees: 4502 )
Refugee.create(countryOfOrigin:"Nigeria", countryOfAsylum:"Chad", refugees: 5689 )
Refugee.create(countryOfOrigin:"Nigeria", countryOfAsylum:"France", refugees: 1250 )
Refugee.create(countryOfOrigin:"Nigeria", countryOfAsylum:"Germany", refugees: 981 )
Refugee.create(countryOfOrigin:"Nigeria", countryOfAsylum:"Italy", refugees: 9931 )
Refugee.create(countryOfOrigin:"Nigeria", countryOfAsylum:"Niger", refugees: 68321 )
Refugee.create(countryOfOrigin:"Nigeria", countryOfAsylum:"United Kingdom", refugees: 1679 )
Refugee.create(countryOfOrigin:"Pakistan", countryOfAsylum:"Afghanistan", refugees: 257523 )
Refugee.create(countryOfOrigin:"Pakistan", countryOfAsylum:"Australia", refugees: 3333 )
Refugee.create(countryOfOrigin:"Pakistan", countryOfAsylum:"Canada", refugees: 7207 )
Refugee.create(countryOfOrigin:"Pakistan", countryOfAsylum:"France", refugees: 961 )
Refugee.create(countryOfOrigin:"Pakistan", countryOfAsylum:"Germany", refugees: 4702 )
Refugee.create(countryOfOrigin:"Pakistan", countryOfAsylum:"Italy", refugees: 9202 )
Refugee.create(countryOfOrigin:"Pakistan", countryOfAsylum:"Thailand", refugees: 554 )
Refugee.create(countryOfOrigin:"Pakistan", countryOfAsylum:"United Kingdom", refugees: 6319 )
Refugee.create(countryOfOrigin:"Pakistan", countryOfAsylum:"United States of America", refugees: 3111 )
Refugee.create(countryOfOrigin:"Palestinian", countryOfAsylum:"Algeria", refugees: 4016 )
Refugee.create(countryOfOrigin:"Palestinian", countryOfAsylum:"Egypt", refugees: 70021 )
Refugee.create(countryOfOrigin:"Palestinian", countryOfAsylum:"Iraq", refugees: 9250 )
Refugee.create(countryOfOrigin:"Palestinian", countryOfAsylum:"Libya", refugees: 5380 )
Refugee.create(countryOfOrigin:"Palestinian", countryOfAsylum:"Turkey", refugees: 906 )
Refugee.create(countryOfOrigin:"Palestinian", countryOfAsylum:"United States of America", refugees: 1237 )
Refugee.create(countryOfOrigin:"Moldova", countryOfAsylum:"Austria", refugees: 15526 )
Refugee.create(countryOfOrigin:"Russia", countryOfAsylum:"Belgium", refugees: 2733 )
Refugee.create(countryOfOrigin:"Russia", countryOfAsylum:"Denmark", refugees: 1026 )
Refugee.create(countryOfOrigin:"Russia", countryOfAsylum:"France", refugees: 14195 )
Refugee.create(countryOfOrigin:"Russia", countryOfAsylum:"Germany", refugees: 4856 )
Refugee.create(countryOfOrigin:"Russia", countryOfAsylum:"Norway", refugees: 1851 )
Refugee.create(countryOfOrigin:"Russia", countryOfAsylum:"Poland", refugees: 12304 )
Refugee.create(countryOfOrigin:"Russia", countryOfAsylum:"Sweden", refugees: 2003 )
Refugee.create(countryOfOrigin:"Russia", countryOfAsylum:"United States of America", refugees: 5905 )
Refugee.create(countryOfOrigin:"Russia", countryOfAsylum:"Canada", refugees: 1620 )
Refugee.create(countryOfOrigin:"Rwanda", countryOfAsylum:"Congo", refugees: 8549 )
Refugee.create(countryOfOrigin:"Rwanda", countryOfAsylum:"Congo", refugees: 245052 )
Refugee.create(countryOfOrigin:"Rwanda", countryOfAsylum:"France", refugees: 2795 )
Refugee.create(countryOfOrigin:"Rwanda", countryOfAsylum:"Malawi", refugees: 2116 )
Refugee.create(countryOfOrigin:"Rwanda", countryOfAsylum:"South Africa", refugees: 1881 )
Refugee.create(countryOfOrigin:"Rwanda", countryOfAsylum:"Uganda", refugees: 14714 )
Refugee.create(countryOfOrigin:"Rwanda", countryOfAsylum:"United States of America", refugees: 1048 )
Refugee.create(countryOfOrigin:"Rwanda", countryOfAsylum:"Zambia", refugees: 1548 )
Refugee.create(countryOfOrigin:"Rwanda", countryOfAsylum:"Canada", refugees: 1778 )
Refugee.create(countryOfOrigin:"Saint Vincent and the Grenadines", countryOfAsylum:"Gambia", refugees: 7392 )
Refugee.create(countryOfOrigin:"Senegal", countryOfAsylum:"Guinea-Bissau", refugees: 8601 )
Refugee.create(countryOfOrigin:"Senegal", countryOfAsylum:"Italy", refugees: 3037 )
Refugee.create(countryOfOrigin:"Senegal", countryOfAsylum:"Austria", refugees: 2199 )
Refugee.create(countryOfOrigin:"Serbia and Kosovo", countryOfAsylum:"France", refugees: 12500 )
Refugee.create(countryOfOrigin:"Serbia and Kosovo", countryOfAsylum:"Germany", refugees: 9157 )
Refugee.create(countryOfOrigin:"Serbia and Kosovo", countryOfAsylum:"Italy", refugees: 2620 )
Refugee.create(countryOfOrigin:"Serbia and Kosovo", countryOfAsylum:"Sweden", refugees: 2390 )
Refugee.create(countryOfOrigin:"Serbia and Kosovo", countryOfAsylum:"Switzerland", refugees: 3158 )
Refugee.create(countryOfOrigin:"Serbia and Kosovo", countryOfAsylum:"United States of America", refugees: 1396 )
Refugee.create(countryOfOrigin:"Serbia and Kosovo", countryOfAsylum:"Austria", refugees: 3406 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Belgium", refugees: 648 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Canada", refugees: 2531 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Denmark", refugees: 1260 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Djibouti", refugees: 12323 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Egypt", refugees: 4491 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Eritrea", refugees: 2485 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Ethiopia", refugees: 256669 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Finland", refugees: 3062 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"France", refugees: 2007 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Germany", refugees: 4860 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Italy", refugees: 13068 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Kenya", refugees: 417920 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Malta", refugees: 1865 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Netherlands", refugees: 17444 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Norway", refugees: 8600 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"South Africa", refugees: 41458 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Sweden", refugees: 21501 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Switzerland", refugees: 4334 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Turkey", refugees: 2364 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Uganda", refugees: 27720 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"United Kingdom", refugees: 6977 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"United States of America", refugees: 2313 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Yemen", refugees: 253215 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Zambia", refugees: 2403 )
Refugee.create(countryOfOrigin:"Somalia", countryOfAsylum:"Central African Rep.", refugees: 40 )
Refugee.create(countryOfOrigin:"South Sudan", countryOfAsylum:"Congo", refugees: 5597 )
Refugee.create(countryOfOrigin:"South Sudan", countryOfAsylum:"Egypt", refugees: 1686 )
Refugee.create(countryOfOrigin:"South Sudan", countryOfAsylum:"Ethiopia", refugees: 281508 )
Refugee.create(countryOfOrigin:"South Sudan", countryOfAsylum:"Kenya", refugees: 95671 )
Refugee.create(countryOfOrigin:"South Sudan", countryOfAsylum:"Sudan", refugees: 194404 )
Refugee.create(countryOfOrigin:"South Sudan", countryOfAsylum:"Uganda", refugees: 199359 )
Refugee.create(countryOfOrigin:"South Sudan", countryOfAsylum:"Australia", refugees: 3556 )
Refugee.create(countryOfOrigin:"Sri Lanka", countryOfAsylum:"Canada", refugees: 8807 )
Refugee.create(countryOfOrigin:"Sri Lanka", countryOfAsylum:"France", refugees: 24220 )
Refugee.create(countryOfOrigin:"Sri Lanka", countryOfAsylum:"Germany", refugees: 3920 )
Refugee.create(countryOfOrigin:"Sri Lanka", countryOfAsylum:"India", refugees: 64208 )
Refugee.create(countryOfOrigin:"Sri Lanka", countryOfAsylum:"Malaysia", refugees: 1545 )
Refugee.create(countryOfOrigin:"Sri Lanka", countryOfAsylum:"Switzerland", refugees: 4989 )
Refugee.create(countryOfOrigin:"Sri Lanka", countryOfAsylum:"United Kingdom", refugees: 5279 )
Refugee.create(countryOfOrigin:"Sri Lanka", countryOfAsylum:"United States of America", refugees: 1313 )
Refugee.create(countryOfOrigin:"Sri Lanka", countryOfAsylum:"Central African Rep.", refugees: 1987 )
Refugee.create(countryOfOrigin:"Sudan", countryOfAsylum:"Chad", refugees: 299750 )
Refugee.create(countryOfOrigin:"Sudan", countryOfAsylum:"Egypt", refugees: 11296 )
Refugee.create(countryOfOrigin:"Sudan", countryOfAsylum:"Ethiopia", refugees: 37785 )
Refugee.create(countryOfOrigin:"Sudan", countryOfAsylum:"France", refugees: 4146 )
Refugee.create(countryOfOrigin:"Sudan", countryOfAsylum:"Israel", refugees: 4647 )
Refugee.create(countryOfOrigin:"Sudan", countryOfAsylum:"Italy", refugees: 2161 )
Refugee.create(countryOfOrigin:"Sudan", countryOfAsylum:"Jordan", refugees: 1815 )
Refugee.create(countryOfOrigin:"Sudan", countryOfAsylum:"Kenya", refugees: 3419 )
Refugee.create(countryOfOrigin:"Sudan", countryOfAsylum:"Norwa", refugees:	 1619 )
Refugee.create(countryOfOrigin:"Sudan", countryOfAsylum:"South Sudan", refugees: 241002 )
Refugee.create(countryOfOrigin:"Sudan", countryOfAsylum:"Uganda", refugees: 1992 )
Refugee.create(countryOfOrigin:"Sudan", countryOfAsylum:"United Kingdom", refugees: 6076 )
Refugee.create(countryOfOrigin:"Sudan", countryOfAsylum:"United States of America", refugees: 1362 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Armenia", refugees: 16611 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Austria", refugees: 14894 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Belgium", refugees: 4239 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Brazil", refugees: 2271 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Bulgaria", refugees: 13819 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Canada", refugees: 1513 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Cyprus", refugees: 3110 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Denmark", refugees: 12988 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Egypt", refugees: 117635 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Finland", refugees: 565 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"France", refugees: 5179 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Germany", refugees: 115604 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Greece", refugees: 9101 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Iraq", refugees: 244642 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Italy", refugees: 1460 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Jordan", refugees: 628223 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Lebanon", refugees: 1062690 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Malta", refugees: 1328 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Morocco", refugees: 2619 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Netherlands", refugees: 16184 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Norway", refugees: 4121 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Russia", refugees: 1304 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Spain", refugees: 1992 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Sudan", refugees: 2692 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Sweden", refugees: 52707 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Switzerland", refugees: 8695 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Turkey", refugees: 2503549 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"United Kingdom", refugees: 6496 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"United States of America", refugees: 5651 )
Refugee.create(countryOfOrigin:"Syria", countryOfAsylum:"Yemen", refugees: 3011 )
Refugee.create(countryOfOrigin:"Tibetan", countryOfAsylum:"Nepal", refugees: 15000 )
Refugee.create(countryOfOrigin:"Togo", countryOfAsylum:"Germany", refugees: 1188 )
Refugee.create(countryOfOrigin:"Togo", countryOfAsylum:"Ghana", refugees: 3041 )
Refugee.create(countryOfOrigin:"Togo", countryOfAsylum:"Italy", refugees: 1430 )
Refugee.create(countryOfOrigin:"Turkey", countryOfAsylum:"Canada", refugees: 1991 )
Refugee.create(countryOfOrigin:"Turkey", countryOfAsylum:"France", refugees: 10652 )
Refugee.create(countryOfOrigin:"Turkey", countryOfAsylum:"Germany", refugees: 20281 )
Refugee.create(countryOfOrigin:"Turkey", countryOfAsylum:"Iraq", refugees: 15557 )
Refugee.create(countryOfOrigin:"Turkey", countryOfAsylum:"Italy", refugees: 2482 )
Refugee.create(countryOfOrigin:"Turkey", countryOfAsylum:"Switzerland", refugees: 3544 )
Refugee.create(countryOfOrigin:"Uganda", countryOfAsylum:"United Kingdom", refugees: 966 )
Refugee.create(countryOfOrigin:"Uganda", countryOfAsylum:"United States of America", refugees: 1231 )
Refugee.create(countryOfOrigin:"Ukraine", countryOfAsylum:"Belarus", refugees: 1089 )
Refugee.create(countryOfOrigin:"Ukraine", countryOfAsylum:"Canada", refugees: 1314 )
Refugee.create(countryOfOrigin:"Ukraine", countryOfAsylum:"France", refugees: 1038 )
Refugee.create(countryOfOrigin:"Ukraine", countryOfAsylum:"Italy", refugees: 1870 )
Refugee.create(countryOfOrigin:"Ukraine", countryOfAsylum:"Russia", refugees: 311407 )
Refugee.create(countryOfOrigin:"Ukraine", countryOfAsylum:"United States of America", refugees: 1486 )
Refugee.create(countryOfOrigin:"Uzbekistan", countryOfAsylum:"United States of America", refugees: 1431 )
Refugee.create(countryOfOrigin:"Venezuela", countryOfAsylum:"United States of America", refugees: 6193 )
Refugee.create(countryOfOrigin:"Vietnam", countryOfAsylum:"China", refugees: 317098 )
Refugee.create(countryOfOrigin:"Vietnam", countryOfAsylum:"France", refugees: 8132 )
Refugee.create(countryOfOrigin:"Vietnam", countryOfAsylum:"Germany", refugees: 1357 )
Refugee.create(countryOfOrigin:"Vietnam", countryOfAsylum:"Switzerland", refugees: 1130 )
Refugee.create(countryOfOrigin:"Western Sahara", countryOfAsylum:"Algeria", refugees: 90000 )
Refugee.create(countryOfOrigin:"Western Sahara", countryOfAsylum:"Mauritania", refugees: 26007 )
Refugee.create(countryOfOrigin:"Yemen", countryOfAsylum:"Djibouti", refugees: 6157 )
Refugee.create(countryOfOrigin:"Yemen", countryOfAsylum:"Ethiopia", refugees: 1088 )
Refugee.create(countryOfOrigin:"Yemen", countryOfAsylum:"Somalia", refugees: 5183 )
Refugee.create(countryOfOrigin:"Zimbabwe", countryOfAsylum:"Australia", refugees: 1009 )
Refugee.create(countryOfOrigin:"Zimbabwe", countryOfAsylum:"Canada", refugees: 2368 )
Refugee.create(countryOfOrigin:"Zimbabwe", countryOfAsylum:"South Africa", refugees: 6358 )
Refugee.create(countryOfOrigin:"Zimbabwe", countryOfAsylum:"United Kingdom", refugees: 9045 )
Refugee.create(countryOfOrigin:"Zimbabwe", countryOfAsylum:"United States of America", refugees: 1316 )
Refugee.create(countryOfOrigin:"Stateless", countryOfAsylum:"Australia", refugees: 1727 )
Refugee.create(countryOfOrigin:"Stateless", countryOfAsylum:"Austria", refugees: 2457 )
Refugee.create(countryOfOrigin:"Stateless", countryOfAsylum:"Denmark", refugees: 1958 )
Refugee.create(countryOfOrigin:"Stateless", countryOfAsylum:"Germany", refugees: 2935 )
Refugee.create(countryOfOrigin:"Stateless", countryOfAsylum:"Netherlands", refugees: 3714 )
Refugee.create(countryOfOrigin:"Stateless", countryOfAsylum:"Norway", refugees: 3005 )
Refugee.create(countryOfOrigin:"Stateless", countryOfAsylum:"Sweden", refugees: 15410 )
Refugee.create(countryOfOrigin:"Stateless", countryOfAsylum:"United Kingdom", refugees: 1407 )
Refugee.create(countryOfOrigin:"Various", countryOfAsylum:"Austria", refugees: 178 )
Refugee.create(countryOfOrigin:"Various", countryOfAsylum:"Belgium", refugees: 8345 )
Refugee.create(countryOfOrigin:"Various", countryOfAsylum:"Ecuador", refugees: 16 )
Refugee.create(countryOfOrigin:"Various", countryOfAsylum:"France", refugees: 68443 )
Refugee.create(countryOfOrigin:"Various", countryOfAsylum:"Germany", refugees: 9089 )
Refugee.create(countryOfOrigin:"Various", countryOfAsylum:"Greece", refugees: 1539 )
Refugee.create(countryOfOrigin:"Various", countryOfAsylum:"Italy", refugees: 1212 )
Refugee.create(countryOfOrigin:"Various", countryOfAsylum:"Netherlands", refugees: 2612 )
Refugee.create(countryOfOrigin:"Various", countryOfAsylum:"Serbia and Kosovo", refugees: 1999 )
Refugee.create(countryOfOrigin:"Various", countryOfAsylum:"Switzerland", refugees: 1173 )
Refugee.create(countryOfOrigin:"Various", countryOfAsylum:"United Kingdom", refugees: 19731 )
Refugee.create(countryOfOrigin:"Various", countryOfAsylum:"United States of America", refugees: 2903 )
