# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Refugee.delete_all
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: -25.2744, asylum_coordinates_y: 133.7751, origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Australia", refugees: 7785 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: 47.5162, asylum_coordinates_y: 14.5501, origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Austria", refugees: 17458 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: 50.5039, asylum_coordinates_y: 4.4699, origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Belgium", refugees: 2934 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: 56.1304, asylum_coordinates_y: -106.3468, origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Canada", refugees: 2890 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Denmark", refugees: 2166 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Finland",	refugees: 1406 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"France", refugees: 4397 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Germany",	refugees: 30026 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Greece", refugees: 5223 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Hungary",	refugees: 942 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"India",	refugees: 10196 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Indonesia",	refugees: 2890 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Iran", refugees: 952 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Italy",	refugees: 12203 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Netherlands",	refugees: 5803)
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Norway", refugees: 5684)
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Pakistan", refugees: 1560592)
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Serbia and Kosovo", refugees: 1999 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Sweden", refugees: 13064 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Switzerland", refugees: 4686 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Syria", refugees: 1213 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Tajikistan", refugees: 1950 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Turkey", refugees: 3846 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"Ukraine", refugees: 1520 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"United Kingdom", refugees: 9354 )
Refugee.create(country_of_origin:"Afghanistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: 33.9391, origin_coordinates_y: 67.7100, country_of_asylum:"United States of America", refugees: 1361 )
Refugee.create(country_of_origin:"Albania", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 2911 )
Refugee.create(country_of_origin:"Albania", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 1823 )
Refugee.create(country_of_origin:"Albania", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 2194 )
Refugee.create(country_of_origin:"Algeria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 1384 )
Refugee.create(country_of_origin:"Angola", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Brazil", refugees: 1083 )
Refugee.create(country_of_origin:"Angola", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 3349 )
Refugee.create(country_of_origin:"Armenia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 4034 )
Refugee.create(country_of_origin:"Armenia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 1191 )
Refugee.create(country_of_origin:"Armenia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 2440 )
Refugee.create(country_of_origin:"Azerbaijan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Armenia", refugees: 1501 )
Refugee.create(country_of_origin:"Azerbaijan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 2816 )
Refugee.create(country_of_origin:"Azerbaijan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 2171 )
Refugee.create(country_of_origin:"Bangladesh", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 3960 )
Refugee.create(country_of_origin:"Bangladesh", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 2545 )
Refugee.create(country_of_origin:"Bangladesh", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 940 )
Refugee.create(country_of_origin:"Bangladesh", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1121 )
Refugee.create(country_of_origin:"Belarus", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1804 )
Refugee.create(country_of_origin:"Bhutan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Nepal", refugees: 17134 )
Refugee.create(country_of_origin:"Bosnia and Herzegovina", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 4055 )
Refugee.create(country_of_origin:"Bosnia and Herzegovina", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 1412 )
Refugee.create(country_of_origin:"Bosnia and Herzegovina", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Serbia and Kosovo", refugees: 9287 )
Refugee.create(country_of_origin:"Bosnia and Herzegovina", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Switzerland", refugees: 2274 )
Refugee.create(country_of_origin:"Burkina Faso", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 929 )
Refugee.create(country_of_origin:"Burundi", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 2074 )
Refugee.create(country_of_origin:"Burundi", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Congo", refugees: 23163 )
Refugee.create(country_of_origin:"Burundi", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Kenya", refugees: 848 )
Refugee.create(country_of_origin:"Burundi", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Malawi", refugees: 1479 )
Refugee.create(country_of_origin:"Burundi", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Rwanda", refugees: 70848 )
Refugee.create(country_of_origin:"Burundi", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"South Africa", refugees: 3819 )
Refugee.create(country_of_origin:"Burundi", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Uganda", refugees: 26256 )
Refugee.create(country_of_origin:"Burundi", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Tanzania", refugees: 155755 )
Refugee.create(country_of_origin:"Burundi", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Zambia", refugees: 2931 )
Refugee.create(country_of_origin:"Cambodia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 11824 )
Refugee.create(country_of_origin:"Cameroon", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 4530 )
Refugee.create(country_of_origin:"Central African Rep.", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Cameroon", refugees: 267463 )
Refugee.create(country_of_origin:"Central African Rep.", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Chad", refugees: 63397 )
Refugee.create(country_of_origin:"Central African Rep.", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Congo", refugees: 23664 )
Refugee.create(country_of_origin:"Central African Rep.", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Congo", refugees: 107929 )
Refugee.create(country_of_origin:"Central African Rep.", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 1607 )
Refugee.create(country_of_origin:"Central African Rep.", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"South Sudan", refugees: 1882 )
Refugee.create(country_of_origin:"Central African Rep.", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sudan", refugees: 1439 )
Refugee.create(country_of_origin:"Chad", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Cameroon", refugees: 1798 )
Refugee.create(country_of_origin:"Chad", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 1232 )
Refugee.create(country_of_origin:"Chad", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sudan", refugees: 8894 )
Refugee.create(country_of_origin:"China", asylum_coordinates_x: -25.2744, asylum_coordinates_y: 133.7751, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Australia", refugees: 2955 )
Refugee.create(country_of_origin:"China", asylum_coordinates_x: 50.5039, asylum_coordinates_y: 4.4699, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Belgium", refugees: 1305 )
Refugee.create(country_of_origin:"China", asylum_coordinates_x: 56.1304, asylum_coordinates_y: -106.3468, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 11415 )
Refugee.create(country_of_origin:"China", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 3260 )
Refugee.create(country_of_origin:"China", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 1406 )
Refugee.create(country_of_origin:"China", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"India", refugees: 110098 )
Refugee.create(country_of_origin:"China", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Netherlands", refugees: 1236 )
Refugee.create(country_of_origin:"China", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Switzerland", refugees: 3022 )
Refugee.create(country_of_origin:"China", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 1837 )
Refugee.create(country_of_origin:"China", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 74020 )
Refugee.create(country_of_origin:"Colombia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Brazil", refugees: 1280 )
Refugee.create(country_of_origin:"Colombia", asylum_coordinates_x: 56.1304, asylum_coordinates_y: -106.3468, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 13666 )
Refugee.create(country_of_origin:"Colombia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Chile", refugees: 1054 )
Refugee.create(country_of_origin:"Colombia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Costa Rica", refugees: 2247 )
Refugee.create(country_of_origin:"Colombia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Ecuador", refugees: 120685 )
Refugee.create(country_of_origin:"Colombia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Panama", refugees: 15593 )
Refugee.create(country_of_origin:"Colombia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 8043 )
Refugee.create(country_of_origin:"Colombia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Venezuela", refugees: 173673 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 3225 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"South Africa", refugees: 6566 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1344 )
Refugee.create(country_of_origin:"Côte d'Ivoire", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 2654 )
Refugee.create(country_of_origin:"Côte d'Ivoire", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Ghana", refugees: 10807 )
Refugee.create(country_of_origin:"Côte d'Ivoire", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Guinea", refugees: 6668 )
Refugee.create(country_of_origin:"Côte d'Ivoire", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 5079 )
Refugee.create(country_of_origin:"Côte d'Ivoire", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Liberia", refugees: 36041 )
Refugee.create(country_of_origin:"Côte d'Ivoire", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Togo", refugees: 2516 )
Refugee.create(country_of_origin:"Côte d'Ivoire", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1574 )
Refugee.create(country_of_origin:"Croatia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Bosnia and Herzegovina", refugees: 6679 )
Refugee.create(country_of_origin:"Croatia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Serbia and Kosovo", refugees: 25962 )
Refugee.create(country_of_origin:"Cuba", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Panama", refugees: 1118 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Angola", refugees: 12944 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: 50.5039, asylum_coordinates_y: 4.4699, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Belgium", refugees: 1008 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Brazil", refugees: 1045 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Burundi", refugees: 53029 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: 56.1304, asylum_coordinates_y: -106.3468, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 3316 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Central African Rep.", refugees: 4798 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Congo", refugees: 12267 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 14182 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 1537 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Kenya", refugees: 12046 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Malawi", refugees: 5361 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Mozambique", refugees: 3415 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Namibia", refugees: 1313 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Rwanda", refugees: 73864 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"South Africa", refugees: 32582 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"South Sudan", refugees: 15916 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Switzerland", refugees: 1346 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Uganda", refugees: 201782 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 1473 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Tanzania", refugees: 55803 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Zambia", refugees: 19293 )
Refugee.create(country_of_origin:"Congo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Zimbabwe", refugees: 5414 )
Refugee.create(country_of_origin:"Egypt", asylum_coordinates_x: -25.2744, asylum_coordinates_y: 133.7751, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Australia", refugees: 1507 )
Refugee.create(country_of_origin:"Egypt", asylum_coordinates_x: 56.1304, asylum_coordinates_y: -106.3468, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 752 )
Refugee.create(country_of_origin:"Egypt", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 636 )
Refugee.create(country_of_origin:"Egypt", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 1397 )
Refugee.create(country_of_origin:"Egypt", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 10852 )
Refugee.create(country_of_origin:"El Salvador", asylum_coordinates_x: 56.1304, asylum_coordinates_y: -106.3468, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 1403 )
Refugee.create(country_of_origin:"El Salvador", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Mexico", refugees: 946 )
Refugee.create(country_of_origin:"El Salvador", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 11273 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: 50.5039, asylum_coordinates_y: 4.4699, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Belgium", refugees: 700 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: 56.1304, asylum_coordinates_y: -106.3468, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 1811 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Denmark", refugees: 3213 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Egypt", refugees: 1405 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Ethiopia", refugees: 155231 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 2208 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 10980 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Israel", refugees: 27812 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 11962 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Kenya", refugees: 1229 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Netherlands", refugees: 10870 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Norway", refugees: 13490 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"South Africa", refugees: 2338 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sudan", refugees: 98676 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sweden", refugees: 20203 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Switzerland", refugees: 21000 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Uganda", refugees: 3401 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 12383 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 4085 )
Refugee.create(country_of_origin:"Eritrea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Yemen", refugees: 1278 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: 56.1304, asylum_coordinates_y: -106.3468, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 2047 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Egypt", refugees: 1085 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 2657 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 1894 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Kenya", refugees: 21229 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Norway", refugees: 2012 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Somalia", refugees: 2756 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"South Africa", refugees: 20324 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"South Sudan", refugees: 4200 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sudan", refugees: 3194 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sweden", refugees: 901 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Switzerland", refugees: 1019 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Uganda", refugees: 1495 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 1006 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 10566 )
Refugee.create(country_of_origin:"Ethiopia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Yemen", refugees: 5645 )
Refugee.create(country_of_origin:"Gambia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 4919 )
Refugee.create(country_of_origin:"Gambia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 1235 )
Refugee.create(country_of_origin:"Gambia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1371 )
Refugee.create(country_of_origin:"Georgia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 2826 )
Refugee.create(country_of_origin:"Ghana", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 2502 )
Refugee.create(country_of_origin:"Ghana", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Togo", refugees: 18476 )
Refugee.create(country_of_origin:"Guatemala", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 8864 )
Refugee.create(country_of_origin:"Guinea", asylum_coordinates_x: 50.5039, asylum_coordinates_y: 4.4699, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Belgium", refugees: 3150 )
Refugee.create(country_of_origin:"Guinea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 6005 )
Refugee.create(country_of_origin:"Guinea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 1626 )
Refugee.create(country_of_origin:"Guinea", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 2862 )
Refugee.create(country_of_origin:"Haiti", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 8807 )
Refugee.create(country_of_origin:"Haiti", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 3445 )
Refugee.create(country_of_origin:"Haiti", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 21508 )
Refugee.create(country_of_origin:"Honduras", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Mexico", refugees: 727 )
Refugee.create(country_of_origin:"Honduras", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 4918 )
Refugee.create(country_of_origin:"Hungary", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 973 )
Refugee.create(country_of_origin:"India", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 3712 )
Refugee.create(country_of_origin:"India", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 4581 )
Refugee.create(country_of_origin:"Indonesia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Papua New Guinea", refugees: 9368 )
Refugee.create(country_of_origin:"Indonesia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 3183 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: -25.2744, asylum_coordinates_y: 133.7751, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Australia", refugees: 5201 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: 47.5162, asylum_coordinates_y: 14.5501, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Austria", refugees: 3379 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 2639 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Denmark", refugees: 2009 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 2417 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 19763 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Iraq", refugees: 8231 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 1573 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Netherlands", refugees: 4125 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Norway", refugees: 1487 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sweden", refugees: 4232 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Switzerland", refugees: 1604 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Turkey", refugees: 5262 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 12667 )
Refugee.create(country_of_origin:"Iran", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 5216 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Armenia", refugees: 1019 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: -25.2744, asylum_coordinates_y: 133.7751, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Australia", refugees: 2925 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: 47.5162, asylum_coordinates_y: 14.5501, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Austria", refugees: 3732 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_x: 50.5039, asylum_coordinates_y: 4.4699, origin_coordinates_y: , country_of_asylum:"Belgium", refugees: 1943 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Bulgaria", refugees: 1339 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 1892 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Egypt", refugees: 4347 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Finland", refugees: 4124 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 4787 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 51396 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Greece", refugees: 4348 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Iran", refugees: 28268 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 3428 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Jordan", refugees: 33256 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Lebanon", refugees: 7234 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Libya", refugees: 2507 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Netherlands", refugees: 12397 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Norway", refugees: 4916 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Serbia and Kosovo", refugees: 7 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sweden", refugees: 23886 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Switzerland", refugees: 3501 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Syria", refugees: 18253 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Turkey", refugees: 24135 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 3014 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 5760 )
Refugee.create(country_of_origin:"Iraq", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Yemen", refugees: 3404 )
Refugee.create(country_of_origin:"Kenya", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Ethiopia", refugees: 3193 )
Refugee.create(country_of_origin:"Kenya", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 2258 )
Refugee.create(country_of_origin:"Kyrgyzstan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 986 )
Refugee.create(country_of_origin:"Laos", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 6944 )
Refugee.create(country_of_origin:"Liberia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Ghana", refugees: 2788 )
Refugee.create(country_of_origin:"Liberia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1266 )
Refugee.create(country_of_origin:"Libya", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Malta", refugees: 1544 )
Refugee.create(country_of_origin:"Libya", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 1138 )
Refugee.create(country_of_origin:"Mali", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Burkina Faso", refugees: 33574 )
Refugee.create(country_of_origin:"Mali", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 4050 )
Refugee.create(country_of_origin:"Mali", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 8334 )
Refugee.create(country_of_origin:"Mali", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Mauritania", refugees: 50233 )
Refugee.create(country_of_origin:"Mali", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Niger", refugees: 56012 )
Refugee.create(country_of_origin:"Mali", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1239 )
Refugee.create(country_of_origin:"Mauritania", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 5066 )
Refugee.create(country_of_origin:"Mauritania", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Mali", refugees: 13539 )
Refugee.create(country_of_origin:"Mauritania", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Senegal", refugees: 13687 )
Refugee.create(country_of_origin:"Mexico", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 6414 )
Refugee.create(country_of_origin:"Mexico", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 4822 )
Refugee.create(country_of_origin:"Myanmar", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Bangladesh", refugees: 231948 )
Refugee.create(country_of_origin:"Myanmar", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"India", refugees: 15735 )
Refugee.create(country_of_origin:"Myanmar", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Japan", refugees: 1826 )
Refugee.create(country_of_origin:"Myanmar", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Malaysia", refugees: 88637 )
Refugee.create(country_of_origin:"Myanmar", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Thailand", refugees: 106349 )
Refugee.create(country_of_origin:"Myanmar", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1999 )
Refugee.create(country_of_origin:"Nepal", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 6605 )
Refugee.create(country_of_origin:"Nigeria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Cameroon", refugees: 71840 )
Refugee.create(country_of_origin:"Nigeria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 4502 )
Refugee.create(country_of_origin:"Nigeria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Chad", refugees: 5689 )
Refugee.create(country_of_origin:"Nigeria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 1250 )
Refugee.create(country_of_origin:"Nigeria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 981 )
Refugee.create(country_of_origin:"Nigeria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 9931 )
Refugee.create(country_of_origin:"Nigeria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Niger", refugees: 68321 )
Refugee.create(country_of_origin:"Nigeria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 1679 )
Refugee.create(country_of_origin:"Pakistan", asylum_coordinates_x: 33.9391, asylum_coordinates_y: 67.7100, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Afghanistan", refugees: 257523 )
Refugee.create(country_of_origin:"Pakistan", asylum_coordinates_x: -25.2744, asylum_coordinates_y: 133.7751, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Australia", refugees: 3333 )
Refugee.create(country_of_origin:"Pakistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 7207 )
Refugee.create(country_of_origin:"Pakistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 961 )
Refugee.create(country_of_origin:"Pakistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 4702 )
Refugee.create(country_of_origin:"Pakistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 9202 )
Refugee.create(country_of_origin:"Pakistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Thailand", refugees: 554 )
Refugee.create(country_of_origin:"Pakistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 6319 )
Refugee.create(country_of_origin:"Pakistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 3111 )
Refugee.create(country_of_origin:"Palestinian", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Algeria", refugees: 4016 )
Refugee.create(country_of_origin:"Palestinian", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Egypt", refugees: 70021 )
Refugee.create(country_of_origin:"Palestinian", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Iraq", refugees: 9250 )
Refugee.create(country_of_origin:"Palestinian", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Libya", refugees: 5380 )
Refugee.create(country_of_origin:"Palestinian", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Turkey", refugees: 906 )
Refugee.create(country_of_origin:"Palestinian", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1237 )
Refugee.create(country_of_origin:"Moldova", asylum_coordinates_x: 47.5162, asylum_coordinates_y: 14.5501, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Austria", refugees: 15526 )
Refugee.create(country_of_origin:"Russia", asylum_coordinates_x: 50.5039, asylum_coordinates_y: 4.4699, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Belgium", refugees: 2733 )
Refugee.create(country_of_origin:"Russia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Denmark", refugees: 1026 )
Refugee.create(country_of_origin:"Russia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 14195 )
Refugee.create(country_of_origin:"Russia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 4856 )
Refugee.create(country_of_origin:"Russia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Norway", refugees: 1851 )
Refugee.create(country_of_origin:"Russia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Poland", refugees: 12304 )
Refugee.create(country_of_origin:"Russia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sweden", refugees: 2003 )
Refugee.create(country_of_origin:"Russia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 5905 )
Refugee.create(country_of_origin:"Russia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 1620 )
Refugee.create(country_of_origin:"Rwanda", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Congo", refugees: 8549 )
Refugee.create(country_of_origin:"Rwanda", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Congo", refugees: 245052 )
Refugee.create(country_of_origin:"Rwanda", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 2795 )
Refugee.create(country_of_origin:"Rwanda", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Malawi", refugees: 2116 )
Refugee.create(country_of_origin:"Rwanda", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"South Africa", refugees: 1881 )
Refugee.create(country_of_origin:"Rwanda", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Uganda", refugees: 14714 )
Refugee.create(country_of_origin:"Rwanda", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1048 )
Refugee.create(country_of_origin:"Rwanda", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Zambia", refugees: 1548 )
Refugee.create(country_of_origin:"Rwanda", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 1778 )
Refugee.create(country_of_origin:"Saint Vincent and the Grenadines", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Gambia", refugees: 7392 )
Refugee.create(country_of_origin:"Senegal", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Guinea-Bissau", refugees: 8601 )
Refugee.create(country_of_origin:"Senegal", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 3037 )
Refugee.create(country_of_origin:"Senegal", asylum_coordinates_x: 47.5162, asylum_coordinates_y: 14.5501, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Austria", refugees: 2199 )
Refugee.create(country_of_origin:"Serbia and Kosovo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 12500 )
Refugee.create(country_of_origin:"Serbia and Kosovo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 9157 )
Refugee.create(country_of_origin:"Serbia and Kosovo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 2620 )
Refugee.create(country_of_origin:"Serbia and Kosovo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sweden", refugees: 2390 )
Refugee.create(country_of_origin:"Serbia and Kosovo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Switzerland", refugees: 3158 )
Refugee.create(country_of_origin:"Serbia and Kosovo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1396 )
Refugee.create(country_of_origin:"Serbia and Kosovo", asylum_coordinates_x: 47.5162, asylum_coordinates_y: 14.5501, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Austria", refugees: 3406 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: 50.5039, asylum_coordinates_y: 4.4699, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Belgium", refugees: 648 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 2531 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Denmark", refugees: 1260 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Djibouti", refugees: 12323 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Egypt", refugees: 4491 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Eritrea", refugees: 2485 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Ethiopia", refugees: 256669 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Finland", refugees: 3062 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 2007 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 4860 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 13068 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Kenya", refugees: 417920 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Malta", refugees: 1865 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Netherlands", refugees: 17444 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Norway", refugees: 8600 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"South Africa", refugees: 41458 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sweden", refugees: 21501 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Switzerland", refugees: 4334 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Turkey", refugees: 2364 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Uganda", refugees: 27720 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 6977 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 2313 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Yemen", refugees: 253215 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Zambia", refugees: 2403 )
Refugee.create(country_of_origin:"Somalia", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Central African Rep.", refugees: 40 )
Refugee.create(country_of_origin:"South Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Congo", refugees: 5597 )
Refugee.create(country_of_origin:"South Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Egypt", refugees: 1686 )
Refugee.create(country_of_origin:"South Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Ethiopia", refugees: 281508 )
Refugee.create(country_of_origin:"South Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Kenya", refugees: 95671 )
Refugee.create(country_of_origin:"South Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sudan", refugees: 194404 )
Refugee.create(country_of_origin:"South Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Uganda", refugees: 199359 )
Refugee.create(country_of_origin:"South Sudan", asylum_coordinates_x: -25.2744, asylum_coordinates_y: 133.7751, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Australia", refugees: 3556 )
Refugee.create(country_of_origin:"Sri Lanka", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 8807 )
Refugee.create(country_of_origin:"Sri Lanka", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 24220 )
Refugee.create(country_of_origin:"Sri Lanka", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 3920 )
Refugee.create(country_of_origin:"Sri Lanka", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"India", refugees: 64208 )
Refugee.create(country_of_origin:"Sri Lanka", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Malaysia", refugees: 1545 )
Refugee.create(country_of_origin:"Sri Lanka", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Switzerland", refugees: 4989 )
Refugee.create(country_of_origin:"Sri Lanka", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 5279 )
Refugee.create(country_of_origin:"Sri Lanka", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1313 )
Refugee.create(country_of_origin:"Sri Lanka", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Central African Rep.", refugees: 1987 )
Refugee.create(country_of_origin:"Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Chad", refugees: 299750 )
Refugee.create(country_of_origin:"Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Egypt", refugees: 11296 )
Refugee.create(country_of_origin:"Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Ethiopia", refugees: 37785 )
Refugee.create(country_of_origin:"Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 4146 )
Refugee.create(country_of_origin:"Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Israel", refugees: 4647 )
Refugee.create(country_of_origin:"Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 2161 )
Refugee.create(country_of_origin:"Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Jordan", refugees: 1815 )
Refugee.create(country_of_origin:"Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Kenya", refugees: 3419 )
Refugee.create(country_of_origin:"Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Norwa", refugees:	 1619 )
Refugee.create(country_of_origin:"Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"South Sudan", refugees: 241002 )
Refugee.create(country_of_origin:"Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Uganda", refugees: 1992 )
Refugee.create(country_of_origin:"Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 6076 )
Refugee.create(country_of_origin:"Sudan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1362 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Armenia", refugees: 16611 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: 47.5162, asylum_coordinates_y: 14.5501, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Austria", refugees: 14894 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: 50.5039, asylum_coordinates_y: 4.4699, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Belgium", refugees: 4239 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Brazil", refugees: 2271 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Bulgaria", refugees: 13819 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 1513 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Cyprus", refugees: 3110 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Denmark", refugees: 12988 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Egypt", refugees: 117635 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Finland", refugees: 565 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 5179 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 115604 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Greece", refugees: 9101 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Iraq", refugees: 244642 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 1460 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Jordan", refugees: 628223 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Lebanon", refugees: 1062690 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Malta", refugees: 1328 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Morocco", refugees: 2619 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Netherlands", refugees: 16184 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Norway", refugees: 4121 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Russia", refugees: 1304 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Spain", refugees: 1992 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sudan", refugees: 2692 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sweden", refugees: 52707 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Switzerland", refugees: 8695 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Turkey", refugees: 2503549 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 6496 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 5651 )
Refugee.create(country_of_origin:"Syria", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Yemen", refugees: 3011 )
Refugee.create(country_of_origin:"Tibetan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Nepal", refugees: 15000 )
Refugee.create(country_of_origin:"Togo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 1188 )
Refugee.create(country_of_origin:"Togo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Ghana", refugees: 3041 )
Refugee.create(country_of_origin:"Togo", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 1430 )
Refugee.create(country_of_origin:"Turkey", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 1991 )
Refugee.create(country_of_origin:"Turkey", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 10652 )
Refugee.create(country_of_origin:"Turkey", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 20281 )
Refugee.create(country_of_origin:"Turkey", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Iraq", refugees: 15557 )
Refugee.create(country_of_origin:"Turkey", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 2482 )
Refugee.create(country_of_origin:"Turkey", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Switzerland", refugees: 3544 )
Refugee.create(country_of_origin:"Uganda", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 966 )
Refugee.create(country_of_origin:"Uganda", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1231 )
Refugee.create(country_of_origin:"Ukraine", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Belarus", refugees: 1089 )
Refugee.create(country_of_origin:"Ukraine", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 1314 )
Refugee.create(country_of_origin:"Ukraine", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 1038 )
Refugee.create(country_of_origin:"Ukraine", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 1870 )
Refugee.create(country_of_origin:"Ukraine", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Russia", refugees: 311407 )
Refugee.create(country_of_origin:"Ukraine", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1486 )
Refugee.create(country_of_origin:"Uzbekistan", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1431 )
Refugee.create(country_of_origin:"Venezuela", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 6193 )
Refugee.create(country_of_origin:"Vietnam", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"China", refugees: 317098 )
Refugee.create(country_of_origin:"Vietnam", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 8132 )
Refugee.create(country_of_origin:"Vietnam", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 1357 )
Refugee.create(country_of_origin:"Vietnam", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Switzerland", refugees: 1130 )
Refugee.create(country_of_origin:"Western Sahara", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Algeria", refugees: 90000 )
Refugee.create(country_of_origin:"Western Sahara", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Mauritania", refugees: 26007 )
Refugee.create(country_of_origin:"Yemen", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Djibouti", refugees: 6157 )
Refugee.create(country_of_origin:"Yemen", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Ethiopia", refugees: 1088 )
Refugee.create(country_of_origin:"Yemen", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Somalia", refugees: 5183 )
Refugee.create(country_of_origin:"Zimbabwe", asylum_coordinates_x: -25.2744, asylum_coordinates_y: 133.7751, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Australia", refugees: 1009 )
Refugee.create(country_of_origin:"Zimbabwe", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Canada", refugees: 2368 )
Refugee.create(country_of_origin:"Zimbabwe", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"South Africa", refugees: 6358 )
Refugee.create(country_of_origin:"Zimbabwe", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 9045 )
Refugee.create(country_of_origin:"Zimbabwe", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 1316 )
Refugee.create(country_of_origin:"Stateless", asylum_coordinates_x: -25.2744, asylum_coordinates_y: 133.7751, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Australia", refugees: 1727 )
Refugee.create(country_of_origin:"Stateless", asylum_coordinates_x: 47.5162, asylum_coordinates_y: 14.5501, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Austria", refugees: 2457 )
Refugee.create(country_of_origin:"Stateless", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Denmark", refugees: 1958 )
Refugee.create(country_of_origin:"Stateless", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 2935 )
Refugee.create(country_of_origin:"Stateless", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Netherlands", refugees: 3714 )
Refugee.create(country_of_origin:"Stateless", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Norway", refugees: 3005 )
Refugee.create(country_of_origin:"Stateless", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Sweden", refugees: 15410 )
Refugee.create(country_of_origin:"Stateless", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 1407 )
Refugee.create(country_of_origin:"Various", asylum_coordinates_x: 47.5162, asylum_coordinates_y: 14.5501, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Austria", refugees: 178 )
Refugee.create(country_of_origin:"Various", asylum_coordinates_x: 50.5039, asylum_coordinates_y: 4.4699, origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Belgium", refugees: 8345 )
Refugee.create(country_of_origin:"Various", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Ecuador", refugees: 16 )
Refugee.create(country_of_origin:"Various", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"France", refugees: 68443 )
Refugee.create(country_of_origin:"Various", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Germany", refugees: 9089 )
Refugee.create(country_of_origin:"Various", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Greece", refugees: 1539 )
Refugee.create(country_of_origin:"Various", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Italy", refugees: 1212 )
Refugee.create(country_of_origin:"Various", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Netherlands", refugees: 2612 )
Refugee.create(country_of_origin:"Various", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Serbia and Kosovo", refugees: 1999 )
Refugee.create(country_of_origin:"Various", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"Switzerland", refugees: 1173 )
Refugee.create(country_of_origin:"Various", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United Kingdom", refugees: 19731 )
Refugee.create(country_of_origin:"Various", asylum_coordinates_x: , asylum_coordinates_y: , origin_coordinates_x: , origin_coordinates_y: , country_of_asylum:"United States of America", refugees: 2903 )
